# -*- coding: utf-8 -*-
"""Veri_Artirma_Pratik_Calismasi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168J2SaUnX9r1DYHPBUL6agRBScBHKqti

# VERİ ARTIRMA PRATİK ÇALIŞMASI

Uygulama anlatımından yola çıkarak istenilen veri artırma yöntemlerini siz deneyin!

*Google Colab Servisine bağlantınızın sağlanması işlemi:*
"""

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

"""Dosya konumunuzu doğrulamak için gereken kodlar:"""

!ls drive

import os
os.chdir("/content/drive/VeriArtirma") # Veri artırma diye bir klasörünüz varsa tabi kendi klasörünüzün ismini yazmalısınız içinde görsellerin olduğu (:
!pwd

!ls #Olmanız gereken yerdeki dosyaları görüntülemenize yarar.

"""**Kütüphane kurulumları**"""

from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

"""### Kullanılacak veri artırma tekniklerini tanımla: aşağıdaki 5 tip veri artırma uygulansın!

*   channel_shift_range (70)
*   zca_whitening
*   fill_mode (reflect)
*   rescale
"""

datagen = ImageDataGenerator(#.............
                             #.............
                             #.............
                             #.............
                             #.............)

"""**Tek bir görsel yükle!**
ChetBaker.jpg dosyasını da deneyebilirsiniz

`img = load_img('ChetBaker.jpg')`
"""

img = load_img('......')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)

"""**Tek görselden 150 tane farklı görsel üret ve Artirilmis_Veri klasörüne .jpeg formatında kaydet.**"""

i = 0

for batch in datagen.flow(x, batch_size=1,
                          save_to_dir='....', 
                          save_format='....'):
    i += ...